### ISSUE TITLE
[feature] enhance loop jobs

### ISSUE THREAD

**Issue by siakro** [akromio/nodejs-core#101]
### Please, describe the feature.

Right now, the loops are supported with the `loop` job. It sounds better if the loops are defined for each type of job using the `forEach` field. Example:

```yaml
- macro: create-attackers
  title: Create the attacker containers
  ini: exec sudo docker pull $(attacker.image)
  forEach: $i = range 1 5
  steps:
    - exec sudo docker run --name $(attacker.container)$(i) $(attacker.image)
```

### Please, describe what problem solving.

Enhance the loops and set to job level for enhancing maintenance.
